module.exports = [
    'Scrapbooking Stickers',
    'Scrapbooking Stickers & Sticker Machines',
    'Scrapbooking Sticker Machines',
    'Scrapbooking Stickers',
    'Smartwatch Stickers',
    'Smartwatch Stickers',
    'Smartwatch Stickers',
    'Smartwatch Stickers',
    'Wall Stickers & Murals',
    'Wall Stickers',
    'Window Stickers & Films',
    'Window Stickers',
    'Sports Fan Decals & Bumper Stickers',
    'Sports Fan Bumper Stickers',
    'Wall Stickers & Murals',
    'Wall Stickers',
    'Trading Card Stickers & Sticker Collections',
];
